use app_error::AppError;

#[tokio::main]
async fn main() -> Result<(), AppError> {


    Ok(())
}